name = "aafu-idbmb"
license = "MIT"
licenselink = "https://github.com/darshanbaral/aafu/blob/master/LICENSE"
description = "Single page portfolio theme with accordion and multiple theme colors with option to toggle between main and alternate theme color"
homepage = "https://github.com/darshanbaral/aafu"
tags = ["portfolio", "single page", "resume"]
features = ["responsive", "dark", "clean"]
min_version = "0.54"

[author]
  name = "Darshan Baral"
  homepage = "https://www.darshanbaral.com/"

[author]
  name = "Bambang Rahmadi KP"
  homepage = "https://idbmb.my.id/"
